package com.example.mypets.ui.theme
import androidx.compose.ui.graphics.Color

val primaryVariant = Color(0xFF006D3D)
val primary = Color(0xFF3A9963)
val onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xffeef6ee)
val light_onPrimaryContainer = Color(0xFF00210F)
val secondary = Color(0xFF1F6C2F)
val onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFA6F5A8)
val light_onSecondaryContainer = Color(0xFF002107)
val tertiary = Color(0xFF6E5E00)
val onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFffd47e)
val light_onTertiaryContainer = Color(0xFF211B00)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFBFDF8)
val light_onBackground = Color(0xFF191C1A)
val surface = Color(0xFFE2E2E2)
val light_surfaceVariant = Color(0xFFDCE5DB)
val light_onSurfaceVariant = Color(0xFF000000)
val light_outline = Color(0xFF717971)
val light_inverseOnSurface = Color(0xFFF0F1EC)
val light_inverseSurface = Color(0xFF2E312E)
val light_inversePrimary = Color(0xFF5DDE93)
val light_surfaceTint = Color(0xFF006D3D)
val light_outlineVariant = Color(0xFFC0C9BF)
val light_scrim = Color(0xFF000000)

val dark_primaryContainer = Color(0xFF00522D)
val dark_onPrimaryContainer = Color(0xFF7BFBAD)
val dark_secondaryContainer = Color(0xFF00531C)
val dark_onSecondaryContainer = Color(0xFFA6F5A8)
val dark_tertiaryContainer = Color(0xFF816b3f)
val dark_onTertiaryContainer = Color(0xFFFDE265)
val dark_background = Color(0xFF191C1A)
val dark_onBackground = Color(0xFFE1E3DE)
val dark_onSurface = Color(0xFFE1E3DE)
val dark_surfaceVariant = Color(0xFF414942)
val dark_onSurfaceVariant = Color(0xFFC0C9BF)
val dark_outline = Color(0xFF8B938A)
val dark_inverseOnSurface = Color(0xFF191C1A)
val dark_inverseSurface = Color(0xFFE1E3DE)
val dark_inversePrimary = Color(0xFF006D3D)
val dark_surfaceTint = Color(0xFF5DDE93)
val dark_outlineVariant = Color(0xFF414942)
val dark_scrim = Color(0xFF000000)


